[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --prefix server --include=dev"]

[phases.build]
cmds = ["cd server && ./node_modules/.bin/tsc"]

[start]
cmd = "node server/dist/index.js"
